name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  integrationtests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: npm install
      - run: npm test

  deploy:
    needs: integrationtests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_email: martijnschermers2@gmail.com
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: share-a-meal-backend